a = input('Digite algo ')
print('qual o tipo {}'.format(type(a)))
print('so tem espaco {} '.format(a.isspace()))
print('E um numero {}'.format(a.isnumeric()))
print('e algabetico {}'.format(a.isalpha()))
print('Esta em maiusculas? {}'.format(a.isupper()))
print('Esta em minusculas? {}'.format(a.islower()))
print('Esta capitalozada? {}'.format(a.istitle()))
print(a)
