a = input('Digite algo ')
print('Foi digitado o seguinte {}, qual o tipo {} '.format(a, type(a)))
print('so tem espaco {} '.format(a.isspace()))
print('E um numero? {}'.format(a.isnumeric()))
print(f'É alfanumerico? {a.isalnum()}')
print('É alfabetico? {}'.format(a.isalpha()))
print('Esta em maiusculas? {}'.format(a.isupper()))
print('Esta em minusculas? {}'.format(a.islower()))
print(f'Esta capitalozada? {a.istitle()}')

